### PR TITLE
Replace defunct connection library with crypton-connection

### PR DESCRIPTION
**Pull request by spencerjanssen**
Addresses #40.

### CODE REVIEW

**Comment by ysangkok** [comment]
@typetetris Would you be able to merge this?

**Comment by spencerjanssen** [comment]
Ping @typetetris @parsonsmatt @jhickner, would you like to take a look at this?

**Comment by ysangkok** [comment]
@spencerjanssen Given that there is no response, you might be able to [take over the package](https://wiki.haskell.org/Taking_over_a_package).

**Comment by typetetris** [comment]
I am not working with Haskell any more, therefore this is fine by me.

Have a nice day!
Eric Wolf

09.03.2024 17:40:16 Janus Troelsen ***@***.***>:

**Comment by spencerjanssen** [comment]
I'd be happy to pitch in as a co-maintainer! May I have access to the GitHub repo and maintainer access on Hackage (where my username is SpencerJanssen)?

**Comment by ysangkok** [comment]
@typetetris You can add Spencer as a maintainer by clicking the "edit" button on https://hackage.haskell.org/package/smtp-mail/maintainers/

**Comment by typetetris** [comment]
@jhickner I was able to add @spencerjanssen  as maintainer on hackage. But either I am too dumb to add him in the github repo as a maintainer or I can't. Could you please take a look?

**Comment by ysangkok** [comment]
@spencerjanssen Since the only change is in the cabal file (and not in the source), you can revise the existing uploaded package at: https://hackage.haskell.org/package/smtp-mail/maintain . That way, the Hackage database space is used more efficiently.

**Comment by spencerjanssen** [comment]
@typetetris thanks for adding me on Hackage!

I'd rather not make a metadata update that I can't also fix upstream.  I'd also like to give the other open PRs some attention.

My suggestion is that we move this repo to another location, perhaps https://github.com/haskell-github-trust?  Given that smtp-mail is largely in maintenance mode and the current maintainers have moved on I think this is the best course of action.

Unless I hear some disagreement by March 28, I plan to:
- Create a copy of this repo in haskell-github-trust
- Begin publishing releases from the new repo
- Open a PR here advertising the new location

Cheers @jhickner @parsonsmatt @typetetris, and thanks for the code!

**Comment by ysangkok** [comment]
Seems like the library was forked to https://github.com/haskell-github-trust/smtp-mail and the new release is up: https://hackage.haskell.org/package/smtp-mail

Thanks Spencer!

**Comment by typetetris** [comment]
No further work will be presumably done in this repo.

**Pull request closed without merging**
