### PR TITLE
add parameter to connectSMTP' to specify hostname

### PR DESCRIPTION
**Pull request by mwotton**
This is a bit of a strawman and it could quite possibly be done better: still, the essence is that I need to specify the hostname of the client sending it, or I get rejected by mail servers for not having an accurate RDNS. getHostname isn't enough, as many domains point to the box I'm using, and I think it's not safe in general to assume a machine has only one.

### CODE REVIEW

**Comment by parsonsmatt** [comment]
Changing the type of a publicly exposed function is a breaking change. I can merge as-is and bump the major version, or we can modify the PR to not change the existing interface and instead add a separate function for this.

**Comment by mwotton** [comment]
hi @parsonsmatt! I'm happy with either, but don't have the time to redo the patch rn.

**Comment by parsonsmatt** [comment]
:+1: I'll merge your work and provide the alternate function, that way we won't have to do a breaking change.

**Comment by mwotton** [comment]
thanks mate :)

**Pull request closed without merging**
